#! /usr/bin/python
'''
    html2Shpaml.py

    Contains elements that utilize the google charts public api to produce charts based on common data

    Copyright (C) 2013  Timothy Edmund Crosley

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
'''

import sys
import codecs
from WebElements import Base
from WebElements.Parser import WebElementTree
from WebElements.MultiplePythonSupport import *
from WebElements.StringUtils import interpretAsString

Base.INDENTATION = "  "

class ShpamlTree(WebElementTree):
    """
        Defines how the tree will be formed when SHPAML is passed in
    """
    def endTag(self):
        """
            Overrides end tag to return None as shpaml syntax does not include end tags
        """
        return ""

    def startTag(self):
        """
            Overrides startTag to render using shpaml condensed syntax
        """
        if not self._tagName:
            return u('')

        self.attributes['name'] = self.fullName()
        self.attributes['style'] = self.style

        startTag = self._tagName
        ID = self.fullId()
        if ID:
            startTag += "#" + ID
        for cssClass in self.classes:
            startTag += "." + cssClass
        startTag += " "

        for key, value in iteritems(self.attributes):
            value = interpretAsString(value)
            if value:
                if value == '<BLANK>':
                    value = ""

                if value == '<EMPTY>':
                    startTag += key + " "
                else:
                    if not " " in value and not '"' in value:
                        startTag += key + '=' + value + ' '
                    else:
                        startTag += key + '="' + value.replace('"', '&quot;') + '" '

        if self._tagSelfCloses:
            startTag = '> ' + startTag
        elif not self.childElements:
            startTag = startTag[:-1] + "\n%(indent)s::comment\n%(indent)s%(indent)sempty " % {"indent":Base.INDENTATION}
        elif len(self.childElements) == 1 and type(self.childElements[0]) == Base.TextNode:
            textNode = self.childElements[0]
            if not "\n" in textNode.text():
                startTag += "| " + textNode.text() + " "
                self.removeChild(textNode)

        return startTag[:-1]


def parseFile(fileName, saveChanges=True):
    """
        Parses an html file and prints its content converted to shpmal to standard out - returning a
        webelement tree representation
    """
    with open(fileName, 'r') as fileObj:
        text = fileObj.read().decode('utf8')
        tree = ShpamlTree(text)

        print(tree.toHTML(formatted=True))

    return tree

def convert(text):
    """
        Takes raw html text and converts it to shpaml
    """
    return ShpamlTree(text).toHTML(formatted=True)

def printDoc():
    """
        Prints documentation on how to use shpaml from the command line
    """
    print("Html2Shpaml 0.1 is a forgiving html to shpaml converter")
    print("usage: Html2Shpaml (filename)")
    print("")
    print("Directly prints Shpaml syntaxt - with can then be redirected into a file")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        printDoc()
    elif len(sys.argv) == 2:
        parseFile(sys.argv[1])
    else:
        printDoc()
